import os
import datetime
from audio_analyzer import analyze_audio
from scene_engine import generate_scenes
from image_generator import process_all_images
from video_editor import create_video
from youtube_uploader import get_authenticated_service, generate_seo_metadata, upload_video
from config import OUTPUT_DIR, FINAL_VIDEO

def run_pipeline():
    print("🚀 Starting AI Documentary Automation Pipeline")
    
    # 1. Analyze Audio
    if not analyze_audio():
        print("Audio analysis failed. Exiting.")
        return

    # 2. Generate Scenes
    scenes = generate_scenes()
    if not scenes:
        print("Scene generation failed. Exiting.")
        return

    # 3. Generate Images via Cloudflare
    image_map = process_all_images(scenes)
    if not image_map:
        print("Image generation failed. Exiting.")
        return

    # 4. Assemble Video
    create_video(scenes, image_map)
    
    print("✅ Video creation completed successfully!")

    # 5. YouTube Upload (Optional, triggered by a separate workflow)
    # This part will be called by the YouTube upload workflow, not directly here.
    # For local testing, you can uncomment and set environment variables.
    # youtube_service = get_authenticated_service()
    # if youtube_service:
    #     video_title = os.environ.get("YOUTUBE_TITLE", "My AI Generated Documentary")
    #     video_description = os.environ.get("YOUTUBE_DESCRIPTION", "A documentary generated by AI.")
    #     video_tags = os.environ.get("YOUTUBE_TAGS", "AI,documentary,automation")
    #     thumbnail_path = os.environ.get("YOUTUBE_THUMBNAIL_PATH")

    #     seo_metadata = generate_seo_metadata(video_title, video_description, video_tags)

    #     # Schedule for 24 hours from now (example)
    #     scheduled_time = datetime.datetime.now(datetime.timezone.utc) + datetime.timedelta(hours=24)

    #     upload_video(
    #         youtube_service,
    #         FINAL_VIDEO,
    #         seo_metadata["title"],
    #         seo_metadata["description"],
    #         seo_metadata["tags"],
    #         seo_metadata["category_id"],
    #         privacy_status="private",
    #         scheduled_date=scheduled_time,
    #         thumbnail_path=thumbnail_path
    #     )
    #     print("✅ YouTube upload process initiated (if configured).")

if __name__ == "__main__":
    run_pipeline()
