import os
import google_auth_oauthlib.flow
import googleapiclient.discovery
import googleapiclient.errors
import datetime
import json
from google.oauth2.credentials import Credentials

SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]

def get_authenticated_service():
    client_id = os.environ.get("YOUTUBE_CLIENT_ID")
    client_secret = os.environ.get("YOUTUBE_CLIENT_SECRET")
    refresh_token = os.environ.get("YOUTUBE_REFRESH_TOKEN")

    if not all([client_id, client_secret, refresh_token]):
        print("Error: YOUTUBE_CLIENT_ID, YOUTUBE_CLIENT_SECRET, or YOUTUBE_REFRESH_TOKEN environment variables not set.")
        return None

    credentials = Credentials(
        token=None,  # Access token will be refreshed
        refresh_token=refresh_token,
        client_id=client_id,
        client_secret=client_secret,
        token_uri="https://oauth2.googleapis.com/token"
    )

    try:
        return googleapiclient.discovery.build(
            "youtube", "v3", credentials=credentials)
    except Exception as e:
        print(f"Error building YouTube service: {e}")
        return None

def generate_seo_metadata(video_title, video_description, video_tags):
    # This function would ideally use an LLM to generate SEO-optimized content.
    # For now, it uses the provided inputs directly.
    # In a real scenario, you\'d integrate with an LLM API here.
    print("Generating SEO metadata (placeholder)...")
    return {
        "title": video_title,
        "description": video_description,
        "tags": video_tags.split(",") if video_tags else [],
        "category_id": "28" # Science & Technology
    }

def upload_video(
    youtube_service,
    file_path,
    title,
    description,
    tags,
    category_id,
    privacy_status="private",
    scheduled_date=None,
    thumbnail_path=None
):
    body = {
        "snippet": {
            "title": title,
            "description": description,
            "tags": tags,
            "categoryId": category_id
        },
        "status": {
            "privacyStatus": privacy_status
        }
    }

    if scheduled_date:
        # YouTube API expects ISO 8601 format
        body["status"]["publishAt"] = scheduled_date.isoformat() + ".000Z"
        body["status"]["privacyStatus"] = "private" # Must be private before scheduling

    insert_request = youtube_service.videos().insert(
        part=",".join(body.keys()),
        body=body,
        media_body=googleapiclient.http.MediaFileUpload(file_path, chunksize=-1, resumable=True)
    )

    print(f"Uploading video: {title}...")
    response = None
    while response is None:
        status, response = insert_request.next_chunk()
        if status:
            print(f"Uploaded {int(status.resumable_progress * 100)}%")

    print(f"Video upload complete. Video ID: {response["id"]}")

    if thumbnail_path and os.path.exists(thumbnail_path):
        print(f"Uploading thumbnail: {thumbnail_path}")
        thumbnail_insert_request = youtube_service.thumbnails().set(
            videoId=response["id"],
            media_body=googleapiclient.http.MediaFileUpload(thumbnail_path)
        )
        thumbnail_insert_request.execute()
        print("Thumbnail uploaded.")

    return response

if __name__ == "__main__":
    # This part is for local testing and demonstration purposes.
    # In the actual workflow, main.py will call these functions.
    print("This script is intended to be called by a GitHub Action.")
    print("Please ensure YOUTUBE_CLIENT_ID, YOUTUBE_CLIENT_SECRET, and YOUTUBE_REFRESH_TOKEN are set as environment variables.")
    print("Also ensure YOUTUBE_VIDEO_PATH, YOUTUBE_TITLE, YOUTUBE_DESCRIPTION, YOUTUBE_TAGS, YOUTUBE_THUMBNAIL_PATH are set.")

    # Example usage (will not run without proper setup):
    # youtube = get_authenticated_service()
    # if youtube:
    #     video_path = os.environ.get("YOUTUBE_VIDEO_PATH")
    #     video_title = os.environ.get("YOUTUBE_TITLE", "My AI Generated Documentary")
    #     video_description = os.environ.get("YOUTUBE_DESCRIPTION", "A documentary generated by AI.")
    #     video_tags = os.environ.get("YOUTUBE_TAGS", "AI,documentary,automation")
    #     thumbnail_path = os.environ.get("YOUTUBE_THUMBNAIL_PATH")

    #     seo_metadata = generate_seo_metadata(video_title, video_description, video_tags)

    #     # Schedule for 24 hours from now (example)
    #     scheduled_time = datetime.datetime.now(datetime.timezone.utc) + datetime.timedelta(hours=24)

    #     upload_video(
    #         youtube,
    #         video_path,
    #         seo_metadata["title"],
    #         seo_metadata["description"],
    #         seo_metadata["tags"],
    #         seo_metadata["category_id"],
    #         privacy_status="private", # Set to public or unlisted after scheduling
    #         scheduled_date=scheduled_time,
    #         thumbnail_path=thumbnail_path
    #     )
